### ISSUE TITLE
Emojis☺☺ (5 Punkte)

### ISSUE THREAD

**Issue by Tony1704** [NerdyStuff/VerteilteSysteme#3]
Implementierung von Emojis in dem Chat. Am besten eigene Emojis von Tizian. Die Emojis sollten über UTF-8 verschickt werden können.

**Comment by aalenaa** [comment]
5 Punkte

**Comment by Tony1704** [comment]
already implemented in v0.5 87ea6017d39e88b3480d897a69928311f6c9db04
