### ISSUE TITLE
Error: IOException in Registration on CLI

### ISSUE THREAD

**Issue by NerdyStuff** [NerdyStuff/VerteilteSysteme#34]
Error: IOException

ErrorStack:

Exception in thread "main" java.lang.NullPointerException
	at CLI.printMessages(CLI.java:84)
	at CLI.<init>(CLI.java:42)
	at Main.main(Main.java:13)

**Comment by NerdyStuff** [comment]
After some changes in Client.java we need to check if the sender of a message is Error or empty, if error, we kann print message; Needs to be implemented in GUI as well!

PRIORITY: HIGH

**Comment by NerdyStuff** [comment]
Also: It is possible taht Client returns only one message object, not a list, so iterator does not work on this. Needs to be checked before applying iterator (causes a nullpointer exception...)

**Comment by Tony1704** [comment]
fixed in commit 50844148a705eeb0197c348b61438801bee39fd8
